# Generated by Django 5.2.1 on 2025-06-01 11:22

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_category_image_category_updated_at_comment_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='articlerevision',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='О себе'),
        ),
    ]
