# Generated by Django 4.2.7 on 2025-10-21 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wiki', '0004_alter_category_options_category_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время модерации'),
        ),
        migrations.AddField(
            model_name='article',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_articles', to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
        migrations.AddField(
            model_name='article',
            name='moderation_notes',
            field=models.TextField(blank=True, verbose_name='Заметки модератора'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('review', 'На модерации'), ('published', 'Опубликовано'), ('rejected', 'Отклонено'), ('archived', 'Архив')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='ArticleMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='article_media/', verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео'), ('audio', 'Аудио'), ('document', 'Документ')], max_length=20, verbose_name='Тип файла')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('display_order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='wiki.article', verbose_name='Статья')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Медиафайл статьи',
                'verbose_name_plural': 'Медиафайлы статей',
                'ordering': ['display_order', '-uploaded_at'],
            },
        ),
    ]
