# Generated by Django 4.2.7 on 2025-10-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_article_moderated_at_article_moderated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='discord',
            field=models.CharField(blank=True, max_length=100, verbose_name='Discord'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram',
            field=models.URLField(blank=True, max_length=255, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vk',
            field=models.URLField(blank=True, max_length=255, verbose_name='VK'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='youtube',
            field=models.URLField(blank=True, max_length=255, verbose_name='YouTube'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
    ]
