# Generated by Django 5.2.7 on 2025-10-24 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_articlelike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_notes',
            field=models.TextField(blank=True, verbose_name='Заметки автора'),
        ),
        migrations.AddField(
            model_name='article',
            name='correction_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок исправления'),
        ),
        migrations.AddField(
            model_name='article',
            name='editor_notes',
            field=models.TextField(blank=True, verbose_name='Заметки редактора'),
        ),
        migrations.AddField(
            model_name='article',
            name='highlighted_corrections',
            field=models.JSONField(blank=True, help_text='JSON с выделенными фрагментами и замечаниями', null=True, verbose_name='Выделенные правки'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('review', 'На модерации'), ('needs_correction', 'Требует правок'), ('editor_review', 'На проверке у редактора'), ('author_review', 'На согласовании у автора'), ('published', 'Опубликовано'), ('rejected', 'Отклонено'), ('archived', 'Архив')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='ModerationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlighted_text', models.TextField(verbose_name='Выделенный текст')),
                ('comment', models.TextField(verbose_name='Замечание')),
                ('start_position', models.IntegerField(default=0, verbose_name='Начальная позиция')),
                ('end_position', models.IntegerField(default=0, verbose_name='Конечная позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('resolved', models.BooleanField(default=False, verbose_name='Исправлено')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Время исправления')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_comments', to='wiki.article')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
            ],
            options={
                'verbose_name': 'Комментарий модератора',
                'verbose_name_plural': 'Комментарии модераторов',
                'ordering': ['created_at'],
            },
        ),
    ]
