# Generated by Django 5.2.7 on 2025-10-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_article_author_notes_article_correction_deadline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, verbose_name='Запрос')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('last_searched', models.DateTimeField(auto_now=True, verbose_name='Последний поиск')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Поисковый запрос',
                'verbose_name_plural': 'Поисковые запросы',
                'ordering': ['-count', '-last_searched'],
            },
        ),
    ]
