# Generated by Django 5.2.7 on 2025-10-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_searchquery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'permissions': [('can_moderate', 'Может модерировать статьи'), ('can_edit_content', 'Может редактировать контент'), ('can_manage_categories', 'Может управлять категориями')], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
