# Generated by Django 5.2.7 on 2025-10-26 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_alter_article_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('content', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('sender_deleted', models.BooleanField(default=False, verbose_name='Удалено отправителем')),
                ('recipient_deleted', models.BooleanField(default=False, verbose_name='Удалено получателем')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
                'permissions': [('can_message_users', 'Может отправлять сообщения пользователям')],
            },
        ),
    ]
