# Generated by Django 5.2.7 on 2025-10-26 14:51

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wiki', '0011_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Введите хештеги через запятую. Например: #ведьмак #монстры #магия', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Хештеги'),
        ),
    ]
