# Generated by Django 5.2.7 on 2025-10-26 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_alter_article_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderationcomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий модератора', 'verbose_name_plural': 'Комментарии модераторов'},
        ),
        migrations.RemoveField(
            model_name='moderationcomment',
            name='resolved',
        ),
        migrations.AddField(
            model_name='moderationcomment',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_comments', to=settings.AUTH_USER_MODEL, verbose_name='Исправил'),
        ),
        migrations.AddField(
            model_name='moderationcomment',
            name='selection_context',
            field=models.TextField(blank=True, help_text='Текст вокруг выделенного фрагмента', verbose_name='Контекст выделения'),
        ),
        migrations.AddField(
            model_name='moderationcomment',
            name='severity',
            field=models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('critical', 'Критическая')], default='medium', max_length=20, verbose_name='Важность'),
        ),
        migrations.AddField(
            model_name='moderationcomment',
            name='status',
            field=models.CharField(choices=[('open', 'Открыто'), ('in_progress', 'В работе'), ('resolved', 'Исправлено'), ('wont_fix', 'Не будет исправлено')], default='open', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='moderationcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
