# Generated by Django 5.2.7 on 2025-11-02 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0015_alter_emailverification_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='ID в Telegram')),
                ('telegram_username', models.CharField(blank=True, max_length=32, verbose_name='Username в Telegram')),
                ('first_name', models.CharField(blank=True, max_length=64, verbose_name='Имя в Telegram')),
                ('last_name', models.CharField(blank=True, max_length=64, verbose_name='Фамилия в Telegram')),
                ('photo_url', models.URLField(blank=True, verbose_name='Фото профиля')),
                ('is_verified', models.BooleanField(default=True, verbose_name='Подтвержден')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата привязки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram пользователь',
                'verbose_name_plural': 'Telegram пользователи',
            },
        ),
    ]
