# Generated by Django 5.2.8 on 2025-11-29 17:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0017_article_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='auth_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата авторизации'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='hash',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Хеш авторизации'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='web_app_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Данные Web App'),
        ),
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='Код')),
                ('telegram_id', models.BigIntegerField(verbose_name='ID Telegram')),
                ('telegram_username', models.CharField(blank=True, max_length=32, verbose_name='Username Telegram')),
                ('first_name', models.CharField(blank=True, max_length=64, verbose_name='Имя')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Время использования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('expires_at', models.FloatField(verbose_name='Истекает')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_auth_codes', to=settings.AUTH_USER_MODEL, verbose_name='Использован пользователем')),
            ],
            options={
                'verbose_name': 'Код авторизации',
                'verbose_name_plural': 'Коды авторизации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramLoginToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Токен')),
                ('telegram_user_id', models.BigIntegerField(verbose_name='ID пользователя Telegram')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Токен входа Telegram',
                'verbose_name_plural': 'Токены входа Telegram',
                'ordering': ['-created_at'],
            },
        ),
    ]
