# Generated by Django 5.2.8 on 2025-11-30 00:45
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0018_telegramuser_auth_date_telegramuser_hash_and_more'),
    ]

    operations = [
        # Фиктивная миграция - поля уже существуют в БД
    ]