# Generated by Django 5.2.8 on 2025-11-30 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wiki', '0019_fix_telegramuser_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('article_create', 'Создание статьи'), ('article_edit', 'Редактирование статьи'), ('article_delete', 'Удаление статьи'), ('article_publish', 'Публикация статьи'), ('article_moderate', 'Модерация статьи'), ('comment_create', 'Создание комментария'), ('comment_delete', 'Удаление комментария'), ('user_register', 'Регистрация пользователя'), ('profile_update', 'Обновление профиля'), ('password_change', 'Смена пароля'), ('category_create', 'Создание категории'), ('category_edit', 'Редактирование категории'), ('category_delete', 'Удаление категории'), ('message_send', 'Отправка сообщения'), ('search', 'Поисковый запрос'), ('system', 'Системное действие')], max_length=50, verbose_name='Тип действия')),
                ('description', models.TextField(verbose_name='Описание действия')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='Браузер')),
                ('operating_system', models.CharField(blank=True, max_length=100, verbose_name='Операционная система')),
                ('action_data', models.JSONField(blank=True, default=dict, verbose_name='Данные действия')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время действия')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог действия',
                'verbose_name_plural': 'Логи действий',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='wiki_action_created_402593_idx'), models.Index(fields=['action_type'], name='wiki_action_action__b89632_idx'), models.Index(fields=['user'], name='wiki_action_user_id_6c352f_idx')],
            },
        ),
    ]
