# Generated by Django 5.2.8 on 2025-11-30 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0020_actionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_seen_welcome', models.BooleanField(default=False, verbose_name='Видел приветственную подсказку')),
                ('has_seen_article_creation', models.BooleanField(default=False, verbose_name='Видел подсказку по созданию статей')),
                ('has_seen_search_tips', models.BooleanField(default=False, verbose_name='Видел подсказку по поиску')),
                ('has_seen_profile_tips', models.BooleanField(default=False, verbose_name='Видел подсказку по профилю')),
                ('tutorial_completed', models.BooleanField(default=False, verbose_name='Обучение завершено')),
                ('show_tutorials', models.BooleanField(default=True, verbose_name='Показывать подсказки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_status', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статус обучения пользователя',
                'verbose_name_plural': 'Статусы обучения пользователей',
            },
        ),
    ]
