# Generated by Django 5.2.8 on 2025-11-30 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0021_usertutorial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertutorial',
            options={'verbose_name': 'Статус подсказок пользователя', 'verbose_name_plural': 'Статусы подсказок пользователей'},
        ),
        migrations.RemoveField(
            model_name='usertutorial',
            name='has_seen_article_creation',
        ),
        migrations.RemoveField(
            model_name='usertutorial',
            name='has_seen_profile_tips',
        ),
        migrations.RemoveField(
            model_name='usertutorial',
            name='has_seen_search_tips',
        ),
        migrations.RemoveField(
            model_name='usertutorial',
            name='show_tutorials',
        ),
        migrations.RemoveField(
            model_name='usertutorial',
            name='tutorial_completed',
        ),
        migrations.AddField(
            model_name='usertutorial',
            name='has_seen_article_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertutorial',
            name='has_seen_categories',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertutorial',
            name='has_seen_messages',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertutorial',
            name='has_seen_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertutorial',
            name='has_seen_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertutorial',
            name='tutorials_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usertutorial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usertutorial',
            name='has_seen_welcome',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usertutorial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usertutorial',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_status', to=settings.AUTH_USER_MODEL),
        ),
    ]
