# Generated by Django 5.2.8 on 2025-11-30 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0022_alter_usertutorial_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название бэкапа')),
                ('backup_type', models.CharField(choices=[('all', 'Все логи'), ('selected', 'Выбранные логи'), ('period', 'За период')], max_length=20, verbose_name='Тип бэкапа')),
                ('format', models.CharField(choices=[('json', 'JSON'), ('pdf', 'PDF')], max_length=10, verbose_name='Формат')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Начальная дата')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Конечная дата')),
                ('selected_logs', models.JSONField(blank=True, default=list, verbose_name='Выбранные логи')),
                ('logs_count', models.PositiveIntegerField(default=0, verbose_name='Количество записей')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Размер файла (байт)')),
                ('backup_file', models.FileField(blank=True, null=True, upload_to='backups/logs/', verbose_name='Файл бэкапа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Бэкап логов',
                'verbose_name_plural': 'Бэкапы логов',
                'ordering': ['-created_at'],
            },
        ),
    ]
