# Generated by Django 6.0 on 2025-12-07 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0023_backuplog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('category', models.CharField(choices=[('general', 'Общая информация'), ('articles', 'Работа со статьями'), ('comments', 'Комментарии'), ('search', 'Поиск и фильтрация'), ('export', 'Экспорт данных'), ('account', 'Управление аккаунтом')], max_length=50, verbose_name='Категория')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Часто задаваемый вопрос',
                'verbose_name_plural': 'Часто задаваемые вопросы',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='HelpSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название раздела')),
                ('section_type', models.CharField(choices=[('general', 'Общая информация'), ('articles', 'Работа со статьями'), ('comments', 'Комментарии'), ('search', 'Поиск и фильтрация'), ('export', 'Экспорт данных'), ('account', 'Управление аккаунтом')], max_length=20, verbose_name='Тип раздела')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Раздел помощи',
                'verbose_name_plural': 'Разделы помощи',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='Всего просмотров')),
                ('total_users', models.PositiveIntegerField(default=0, verbose_name='Всего пользователей')),
                ('total_articles', models.PositiveIntegerField(default=0, verbose_name='Всего статей')),
                ('total_comments', models.PositiveIntegerField(default=0, verbose_name='Всего комментариев')),
                ('active_users', models.PositiveIntegerField(default=0, verbose_name='Активных пользователей')),
            ],
            options={
                'verbose_name': 'Статистика сайта',
                'verbose_name_plural': 'Статистика сайта',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='searchquery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Поисковый запрос', 'verbose_name_plural': 'Поисковые запросы'},
        ),
        migrations.RemoveField(
            model_name='searchquery',
            name='count',
        ),
        migrations.RemoveField(
            model_name='searchquery',
            name='last_searched',
        ),
        migrations.AddField(
            model_name='searchquery',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='results_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Найдено результатов'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата поиска'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='query',
            field=models.CharField(max_length=255, verbose_name='Поисковый запрос'),
        ),
        migrations.CreateModel(
            name='ArticleStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Лайки')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='Комментарии')),
                ('last_viewed', models.DateTimeField(auto_now=True, verbose_name='Последний просмотр')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='wiki.article')),
            ],
            options={
                'verbose_name': 'Статистика статьи',
                'verbose_name_plural': 'Статистика статей',
            },
        ),
        migrations.CreateModel(
            name='CategoryStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='Всего просмотров')),
                ('total_articles', models.PositiveIntegerField(default=0, verbose_name='Всего статей')),
                ('avg_rating', models.FloatField(default=0.0, verbose_name='Средний рейтинг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='wiki.category')),
            ],
            options={
                'verbose_name': 'Статистика категории',
                'verbose_name_plural': 'Статистика категорий',
            },
        ),
        migrations.DeleteModel(
            name='BackupLog',
        ),
    ]
