# Generated by Django 6.0 on 2025-12-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0024_faq_helpsection_sitestat_alter_searchquery_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('file_path', models.CharField(max_length=500, verbose_name='Путь к файлу')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Размер файла (байты)')),
                ('backup_type', models.CharField(choices=[('full', 'Полная копия'), ('database', 'Только база данных'), ('media', 'Только медиафайлы')], default='full', max_length=20, verbose_name='Тип бэкапа')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
            ],
            options={
                'verbose_name': 'Резервная копия',
                'verbose_name_plural': 'Резервные копии',
                'ordering': ['-created_at'],
            },
        ),
    ]
