# Generated by Django 6.0 on 2025-12-09 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0026_alter_searchquery_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchquery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Поисковый запрос', 'verbose_name_plural': 'Поисковые запросы'},
        ),
        migrations.RemoveField(
            model_name='searchquery',
            name='count',
        ),
        migrations.RemoveField(
            model_name='searchquery',
            name='last_searched',
        ),
        migrations.AddField(
            model_name='searchquery',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='results_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Найдено результатов'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата поиска'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='query',
            field=models.CharField(max_length=255, verbose_name='Поисковый запрос'),
        ),
    ]
