# Generated by Django 6.0 on 2025-12-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0027_alter_searchquery_options_remove_searchquery_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchquery',
            options={'ordering': ['-count', '-last_searched'], 'verbose_name': 'Поисковый запрос', 'verbose_name_plural': 'Поисковые запросы'},
        ),
        migrations.AddField(
            model_name='searchquery',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='last_searched',
            field=models.DateTimeField(auto_now=True, verbose_name='Последний поиск'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='query',
            field=models.CharField(max_length=255, verbose_name='Запрос'),
        ),
    ]
