# Generated by Django 6.0 on 2025-12-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0032_alter_comment_options_alter_commentlike_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Одобрен'),
        ),
    ]
