# Generated by Django 6.0 on 2025-12-12 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0033_comment_is_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('warning_issued', 'Выдано предупреждение'), ('ban_issued', 'Выдан бан'), ('ban_removed', 'Бан снят'), ('content_removed', 'Контент удален'), ('content_restored', 'Контент восстановлен'), ('user_promoted', 'Пользователь повышен'), ('user_demoted', 'Пользователь понижен')], max_length=50, verbose_name='Тип действия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('details', models.JSONField(default=dict, verbose_name='Детали действия')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('target_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_logs', to=settings.AUTH_USER_MODEL, verbose_name='Целевой пользователь')),
            ],
            options={
                'verbose_name': 'Лог модерации',
                'verbose_name_plural': 'Логи модерации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('censorship', 'Нецензурная лексика'), ('spam', 'Спам'), ('harassment', 'Оскорбления/Троллинг'), ('rules_violation', 'Нарушение правил'), ('multiple_violations', 'Множественные нарушения'), ('other', 'Другое')], max_length=50, verbose_name='Причина бана')),
                ('duration', models.CharField(choices=[('1h', '1 час'), ('24h', '1 день'), ('72h', '3 дня'), ('168h', '1 неделя'), ('720h', '1 месяц'), ('8760h', '1 год'), ('permanent', 'Навсегда')], max_length=20, verbose_name='Длительность бана')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Время начала бана')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания бана')),
                ('notes', models.TextField(blank=True, verbose_name='Дополнительные заметки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Бан активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_bans', to=settings.AUTH_USER_MODEL, verbose_name='Забанен администратором')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бан пользователя',
                'verbose_name_plural': 'Баны пользователей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.IntegerField(choices=[(1, 'Легкое предупреждение'), (2, 'Предупреждение'), (3, 'Серьезное предупреждение'), (4, 'Последнее предупреждение')], default=2, verbose_name='Уровень серьезности')),
                ('reason', models.TextField(verbose_name='Причина предупреждения')),
                ('related_content', models.CharField(blank=True, max_length=500, verbose_name='Связанный контент (URL или описание)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Предупреждение активно')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_warnings', to=settings.AUTH_USER_MODEL, verbose_name='Выдано администратором')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_warnings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Официальное предупреждение',
                'verbose_name_plural': 'Официальные предупреждения',
                'ordering': ['-created_at'],
            },
        ),
    ]
