# Generated by Django 6.0 on 2025-12-12 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0034_moderationlog_userban_userwarning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderationlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userban',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userwarning',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='moderationlog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='moderationlog',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='userban',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='userban',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='userwarning',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='userban',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='action_type',
            field=models.CharField(choices=[('ban', 'Бан'), ('unban', 'Разбан'), ('warning', 'Предупреждение'), ('remove_warning', 'Удаление предупреждения'), ('edit_article', 'Редактирование статьи'), ('delete_article', 'Удаление статьи')], max_length=50),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='target_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userban',
            name='banned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_bans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userban',
            name='duration',
            field=models.IntegerField(choices=[(1, '1 день'), (3, '3 дня'), (7, '1 неделя'), (30, '1 месяц'), (0, 'Навсегда')], default=1),
        ),
        migrations.AlterField(
            model_name='userban',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userban',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userban',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userban',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userwarning',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userwarning',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_warnings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userwarning',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userwarning',
            name='related_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userwarning',
            name='severity',
            field=models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], default='low', max_length=10),
        ),
        migrations.AlterField(
            model_name='userwarning',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to=settings.AUTH_USER_MODEL),
        ),
    ]
