# Generated by Django 6.0 on 2025-12-13 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0035_alter_moderationlog_options_alter_userban_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CensorshipWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Текст с нарушением')),
                ('source_url', models.CharField(max_length=200, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата нарушения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='censorship_warnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Нарушение цензуры',
                'verbose_name_plural': 'Нарушения цензуры',
                'ordering': ['-created_at'],
            },
        ),
    ]
