# Generated by Django 6.0 on 2025-12-13 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0036_censorshipwarning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userban',
            options={'ordering': ['-created_at'], 'verbose_name': 'Бан пользователя', 'verbose_name_plural': 'Баны пользователей'},
        ),
        migrations.AlterModelOptions(
            name='userwarning',
            options={'ordering': ['-created_at'], 'verbose_name': 'Предупреждение пользователя', 'verbose_name_plural': 'Предупреждения пользователей'},
        ),
        migrations.AlterField(
            model_name='userban',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='userban',
            name='duration',
            field=models.CharField(choices=[('1h', '1 час'), ('12h', '12 часов'), ('1d', '1 день'), ('3d', '3 дня'), ('7d', '7 дней'), ('30d', '30 дней'), ('permanent', 'Постоянно')], max_length=20, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='userban',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='userban',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='userban',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='userban',
            name='reason',
            field=models.CharField(choices=[('spam', 'Спам и реклама'), ('abuse', 'Оскорбления и харассмент'), ('hate_speech', 'Разжигание ненависти'), ('fake_news', 'Распространение ложной информации'), ('illegal_content', 'Незаконный контент'), ('multiple_violations', 'Множественные нарушения'), ('other', 'Другое')], max_length=50, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='userwarning',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='userwarning',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='userwarning',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_warnings', to=settings.AUTH_USER_MODEL, verbose_name='Кем выдано'),
        ),
        migrations.AlterField(
            model_name='userwarning',
            name='reason',
            field=models.TextField(verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='userwarning',
            name='related_content',
            field=models.TextField(blank=True, verbose_name='Связанный контент'),
        ),
        migrations.AlterField(
            model_name='userwarning',
            name='severity',
            field=models.CharField(choices=[('low', 'Низкое'), ('medium', 'Среднее'), ('high', 'Высокое'), ('critical', 'Критическое')], default='low', max_length=20, verbose_name='Уровень серьезности'),
        ),
        migrations.AlterField(
            model_name='userwarning',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_warnings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
